source 'https://rubygems.org'

gem 'berkshelf'

# For Chefspec: https://github.com/sethvargo/chefspec
gem 'chefspec'

# For Test Kitchen: https://github.com/test-kitchen/test-kitchen
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-inspec'
