---
driver:
  name: ec2
  aws_ssh_key_id: login-dev-us-west-2
  region: us-west-2
  subnet_filter:
    tag: Name
    value: login-jumphost_subnet-dev
  security_group_filter:
    tag: Name
    value: login-jumphost_security_group-dev
  instance_type: t2.medium

transport:
  username: ubuntu
  ssh_key: ~/.ssh/login-dev-us-west-2.pem

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  environments_path: kitchen/environments
  roles_path: kitchen/roles
  data_bags_path: kitchen/data_bags
  client_rb:
    environment: unittest
  require_chef_omnibus: 12.15

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[example]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      integration_test_mode: true
