---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  environments_path: kitchen/environments
  roles_path: kitchen/roles
  data_bags_path: kitchen/data_bags
  client_rb:
    environment: unittest
  require_chef_omnibus: 12.15

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cookbook_example::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
