#!/bin/bash

set -eu

run() {
    echo >&2 "+ $*"
    "$@"
}

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") SSH_KEY GIT_ARGS...

Run git with GIT_ARGS, using SSH_KEY for ssh.

SSH_KEY should be the path to an SSH private key.

In git 2.3+, this will use GIT_SSH_COMMAND.
In git 1.9.1, this will use GIT_SSH with the ssh-with-key wrapper script.
EOM
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

ssh_key_path="$1"
shift

case "$(git --version)" in
    "git version 1."* \
    | "git version 2.0."* \
    | "git version 2.1."* \
    | "git version 2.2."*)
        # rely on ssh-with-key created by provision.sh
        run env GIT_SSH="/usr/local/bin/ssh-with-key" SSH_KEY_PATH="$ssh_key_path" git "$@"
        ;;
    "git version 2."*)
        run env GIT_SSH_COMMAND="ssh -i '$ssh_key_path'" git "$@"
        ;;
    *)
        echo >&2 "Unexpected git version"
        git --version >&2
        exit 1
        ;;
esac
