#!/bin/sh
set -eu

if [ "$(id -u)" -ne 0 ]; then
    set -x
    exec sudo "$0" "$@"
fi

run() {
    echo >&2 "+ $*"
    "$@"
}

trap 'echo "$(hostname -f) FAILED apt upgrade"' EXIT

run apt-get update

# Run apt-get upgrade in non-interactive mode, keeping existing conf files when
# there are conflicts
# https://raphaelhertzog.com/2010/09/21/debian-conffile-configuration-file-managed-by-dpkg/
run apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y

trap - EXIT
echo 'All done'
