#!/bin/bash
  
#### Purge KMS logs and enable sending KMS logs to CloudWatch ####

set -eu

LOG_DIR='/srv/idp/shared/log'
KMS_LOG='kms.log'

# Verify that KMS is not currently enabled
case `grep "\"file_path\": \"${LOG_DIR}/${KMS_LOG}\"" /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json >/dev/null; echo $?` in
  0) # KMS is already enabled
    echo "No action needed. KMS logging to CloudWatch is already enabled"
    exit 0
    ;;
  1) # KMS is not already enabled 
    ;;
  *) # An error has occurred
    echo "ERROR: Error occurred while determining if KMS needs to be enabled: $?"
    ;;
esac

# Purge KMS Log
> $LOG_DIR/$KMS_LOG

# Update CloudWatch Agent Config to enable sending of KMS Log
sed -i "s~\"file_path\": \"${LOG_DIR}/${KMS_LOG}disabled\"~\"file_path\": \"${LOG_DIR}/${KMS_LOG}\"~g" /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

# Restart the CloudWatch Agent
systemctl restart amazon-cloudwatch-agent.service
