# frozen_string_literal: true

ruby '3.2.2'

source 'https://rubygems.org'

group 'test' do
  gem 'rspec', '~> 3.10'
  gem 'rspec_junit_formatter', '~> 0.4'
end

gem 'aws-sdk-cloudwatch', '~> 1'
gem 'aws-sdk-cloudwatchevents', '~> 1'
gem 'rexml'
