#!/bin/bash
set -eu

run() {
  echo >&2 "+ $*"
  "$@"
}

raise() {
  echo -e "\nERROR: $* \n" >&2
  usage
  exit 1
}

usage() {
  cat >&2 <<EOM
usage: $(basename "$0") TEST_NAME ENV [-c CLIENTS] [-h HATCH_RATE] [-n NUM_USERS]

  TEST_NAME : name of the test, i.e. load_testing/TEST_NAME.locustfile.py
  ENV : environment where test will be pointed, in the format:
         - https://idp.ENV.identitysandbox.gov/
           (will automatically change the URL if set to 'staging' or 'prod')

Optional arguments:
    
    -c : --clients=   (defaults to 1)
    -h : --hatch-rate (defaults to 1)
    -n : NUM_USERS=   (defaults to 100)

Examples:

    $(basename "$0") sign_up pt
    $(basename "$0") sign_up int -c 10 -h 25
    $(basename "$0") sign_in dev -h 10 -n 120

EOM
}

REPO_DIR='/etc/login.gov/repos/identity-loadtest'
[[ -d "${REPO_DIR}" ]] || raise "REPO_DIR ${REPO_DIR} does not exist"

[[ $# -lt 2 ]] && raise "Both TEST_NAME and ENV must be provided"
TEST_FILE="${REPO_DIR}/load_testing/${1}.locustfile.py"
[[ -f "${TEST_FILE}" ]] || raise "Test '${TEST_FILE}' not found"

case "${2}" in
       -*) raise "Invalid environment name: ${2}"         ;;
  staging) TARGET='https://idp.staging.login.gov/'        ;;
     prod) TARGET='https://secure.login.gov/'             ;;
        *) TARGET="https://idp.${2}.identitysandbox.gov/" ;;
esac
shift 2

declare {CLIENTS,HATCH_RATE,NUM_CLIENTS}=1
while getopts c:h:n: opt
do
  case "${opt}" in
    c) CLIENTS=${OPTARG}     ;;
    h) HATCH_RATE=${OPTARG}  ;;
    n) NUM_CLIENTS=${OPTARG} ;;
    :) raise "-${OPTARG} requires argument" ;;
   \?) raise "Invalid option: -${OPTARG}" ;;
  esac
done

run locust --host "${TARGET}" --clients="${CLIENTS}" --hatch-rate "${HATCH_RATE}" --locustfile "${TEST_FILE}" --no-web
