plugins:
  brakeman:
    enabled: true
  reek:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-78
    config:
      file: .rubocop.yml

checks:
  method-complexity:
    enabled: false
