---
detectors:
  Attribute:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NilCheck:
    enabled: false
  TooManyMethods:
    exclude:
      - Certificate
directories:
  'spec':
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    NestedIterators:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
    TooManyMethods:
      enabled: false
    TooManyStatements:
      enabled: false
    UtilityFunction:
      enabled: false
exclude_paths:
  - db/migrate
  - lib/deploy
  - app/services/ocsp_service.rb