# There's nothing wrong with `if x > 0`
Style/NumericPredicate:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

# empty lines are fine
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLines:
  Enabled: false

# Spaces before argument default values are ugly
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# The <<~ operator isn't super widely supported yet
Layout/IndentHeredoc:
  Enabled: false

# trailing commas improve diff clarity at no cost to readability
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# All of these Metrics/* cops are extremely subjective and border on useless.
# When in doubt, use judgment for what actually makes for more readable code.

# Lots of methods will be longer than 10 lines
Metrics/MethodLength:
  Enabled: false

# Who are these people who have such tiny classes?
Metrics/ClassLength:
  Max: 500

# It's not clear that this metric is useful at all
Metrics/AbcSize:
  Enabled: false

# CLI scripts will have long optparse blocks
Metrics/BlockLength:
  Exclude:
    - "**/bin/*"

# Not clear whether this is useful at all
Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Enabled: false

# Parameters are fine
Metrics/ParameterLists:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

# Constants with lowercase are fine
Naming/ConstantName:
  Enabled: false

# $PROGRAM_NAME is not less surprising than $0
Style/SpecialGlobalVars:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
  # Prefer do...end for procedural blocks, {...} for functional
  #EnforcedStyle: semantic

# This default recommendation is bananas
Style/ConditionalAssignment:
  Enabled: false

# Sometimes a `return` enhances clarity
Style/RedundantReturn:
  Enabled: false

# Very frequently if/unless as modifier reduces clarity
Style/IfUnlessModifier:
  Enabled: false

# %w[] is a convenience thing, not a clarity thing
Style/WordArray:
  Enabled: false

# not useful
SpaceInsideHashLiteralBraces:
  Enabled: false

# not useful
Style/IfInsideElse:
  Enabled: false
Style/NegatedIf:
  Enabled: false

# increases errors for little benefit
Style/LineEndConcatenation:
  Enabled: false

# sometimes using self enhances clarity
Style/RedundantSelf:
  Enabled: false

# __FILE__ == $0 is idiomatic, not backwards
Style/YodaCondition:
  Exclude:
    - "**/bin/*"
