source 'https://api.berkshelf.com'

cookbook 'application_ruby'
cookbook 'apt'
cookbook 'bash-completion'
cookbook 'build-essential'
cookbook 'cacert'
cookbook 'git'
cookbook 'hostname'
cookbook 'letsencrypt', '~> 1.0.0'
cookbook 'monit'
cookbook 'motd'
cookbook 'nano'
cookbook 'newrelic'
cookbook 'newrelic_meetme_plugin'
cookbook 'ntp'
cookbook 'ohai'
cookbook 'openssl'
cookbook 'ruby_rbenv'
cookbook 'poise-ruby'
cookbook 'ruby_build'
cookbook 'ssh-keys'
cookbook 'sudo'
cookbook 'users'
cookbook 'jenkins', '~> 4.1.2'
cookbook 'apache2'
cookbook 'acme'
cookbook 'ssh_known_hosts'
cookbook 'terraform'
cookbook 'docker'
cookbook 'filebeat', '~> 0.4.2'
cookbook 'elasticsearch-curator', '~> 0.1.3'


cookbook 'login_dot_gov', path: 'kitchen/cookbooks/login_dot_gov'
cookbook 'passenger', path: 'kitchen/cookbooks/passenger'
cookbook 'poise-ruby-build', path: 'kitchen/cookbooks/poise-ruby-build'
cookbook 'identity-jenkins', path: 'kitchen/cookbooks/identity-jenkins'
cookbook 'identity-elk', path: 'kitchen/cookbooks/identity-elk'

