#!/usr/bin/env bash

# function to exit process with error message
die() { echo_red "$*" >&2 ; exit 1; }

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

if [ $# -lt 3 ] ; then
    echo "Usage: $0 <environment_name> <username> <terraform_dir> [<terraform_commands>]"
    echo "   Runs <terraform_commands> against <environment_name> using the"
    echo "   configuration in <terraform_dir>."
    echo "   <username> should be the username of an existing chef user that"
    echo "   Terraform can use to provision chef-client on new nodes."
    exit 1
fi

# shellcheck source=./bin/lib/common.sh
. "$(dirname "$0")/bin/lib/common.sh"

ENVIRONMENT=$1; shift
GSA_USERNAME=$1; shift
TF_DIR=$1; shift
TF_CMD=("$@")

# We need to be in the root of the repo for all this to work.
cd "$(dirname "$0")"

echo "DEPLOY: Checking whether environment versioning is recommended...."
case "$ENVIRONMENT" in
    prod|staging|int|dm|qa|pt|dev)
    case "$TF_DIR" in
        terraform-app)
        if [[ ( "$(cat VERSION.txt)" =~ -pre ||
                ! "$(git log -n 1 --pretty=format:'%d')" =~ tag: ) ]]; then
                echo_yellow >&2 "



###############################################################################
#                             !!!WARNING!!!                                   #
###############################################################################

The $ENVIRONMENT environment should not be deployed from anything besides a
tagged, non prerelease version because it is one of the environments officially
supported by the devops team, either for clients or for other teams.

See https://github.com/18F/identity-devops/tree/master/doc/process/releases.md
for more details about our release tools.



"
        fi
        ;;
    esac
    ;;
esac

echo_blue "deploy environment: $ENVIRONMENT"

echo "DEPLOY: Loading environment variables...."
. bin/load-env.sh "$ENVIRONMENT" "$GSA_USERNAME"

# Check that current version of terraform is supported by our environment. This
# array should be set in the environment-specific variables.
check_terraform_version "${ID_SUPPORTED_TERRAFORM_VERSIONS[@]}"

echo "DEPLOY: Checking for required files...."
run bin/check-required-files.sh "$ENVIRONMENT"

if [ -z "${TF_VAR_chef_id:=}" ] ; then
    die "You must specify an initial chef user.  \
Make sure $ID_ENV_DIR/$ENVIRONMENT.sh contains all the necessary configuration."
fi

if [ -z "${TF_VAR_chef_id:=}" ] ; then
    die "You must specify an environment to terraform.  \
Make sure $ID_ENV_DIR/$ENVIRONMENT.sh contains all the necessary configuration."
fi

# Terraform will try all SSH identities, even if an earlier one would succeed.
# This hits the max auth attempts limit pretty reliably, so warn about this
# case.  We can probably remove this once we have the max auth limit raised
# higher than any anticipated number of SSH keys in our ssh-agent, or when
# the fix described in identity-devops-private#191 makes its way into a
# Terraform client release.
if [ $(ssh-add -l | wc -l) -gt 4 ]; then
    echo_yellow >&2 '
WARNING: You have more than 4 SSH identities in your ssh-agent.  If
you experience problems setting up Chef (with "Too many authentication
failures for ubuntu"), try reducing the number of identities using
"ssh-add -d ..." until you get this number below 4.  For details,
see https://github.com/18F/identity-devops-private/issues/191.
'
    run ssh-add -l >&2
    echo >&2
fi

STATE=${TF_DIR}/terraform-${TF_VAR_env_name}.tfstate
case "$TF_DIR" in
    terraform-dns|terraform-cloudtrail)
        echo "Not using a region specific state file for dns remote config"
        STATE=${TF_DIR}/terraform.tfstate
        ;;
esac
echo "Using state file $STATE"

echo "Ensuring ${TF_DIR} is a terraform directory"
# NOTE: JJG remove trailing slash from $2 if it exists to ease use with auto completion
if [ ! -f "${TF_DIR}/main.tf" ] ; then
    echo_red "deploy: not found: '${TF_DIR}/main.tf'"
    echo_red "Are you sure '${TF_DIR}' is a terraform project folder?"
    echo_red "Known examples include terraform-app, etc."
    die "error: Could not find terraform files"
fi

echo "Configuring state bucket login_dot_gov_tf_state with state path ${STATE}"
run bin/configure_state_bucket.sh login_dot_gov_tf_state "$STATE" "$TF_DIR" us-east-1

echo >&2 "+ cd $TF_DIR"
cd "$TF_DIR"

cat <<EOF
########################################
#
# Working in environment:
# $TF_VAR_env_name
#
########################################
EOF

echo_blue "Running terraform..."
echo

run terraform get
run terraform "${TF_CMD[@]}"
