#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

if [ $# -lt 1 ] ; then
    echo "Usage: $0 <environment name> [<terraform_commands>]"
    exit 1
fi

export AWS_DEFAULT_REGION=us-west-2
export TF_VAR_env_name=$1; shift
TF_CMD="$@"
TF_DIR="terraform-analytics"
STATE=${TF_DIR}/terraform-${TF_VAR_env_name}.tfstate

echo "Configuring state bucket login_dot_gov_tf_state with state path ${STATE}"
bash -x bin/configure_state_bucket.sh login-dot-gov-analytics-terraform-state "${STATE}" "${TF_DIR}" "us-west-2" "terraform_locks"

cat <<EOF
########################################
#
# Working in environment:
# $TF_VAR_env_name
#
########################################
EOF

cd ${TF_DIR}
terraform get
terraform init "${TF_DIR}"
terraform ${TF_CMD}
