include:
  local: /.gitlab-ci-rules.yml

check_aws_ip_cidr_ranges:
  image: cimg/ruby:3.3
  script:
    - ./bin/oneoffs/update-aws-cidrs
    - |
      (! git diff --name-only | grep "^kitchen/cookbooks/login_dot_gov/templates/default/aws_ipv.*_cidrs\.txt$") || (echo "Error: Run './bin/oneoffs/update-aws-cidrs' to update AWS CIDRs"; exit 1)

check_valid_json_chef:
  image: cimg/ruby:3.3
  script:
    - ./bin/oneoffs/check_valid_json_chef

check_domain_allowlists:
  image: cimg/ruby:3.3
  script:
    - ./bin/oneoffs/check_valid_domain_allowlist 'kitchen/cookbooks/identity-outboundproxy/templates/**/*domain*list*'
