include:
  local: /.gitlab-ci-rules.yml

terraform-fmt:
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  script:
    - terraform fmt -recursive -diff -check ./terraform
  rules:
    - !reference [.merge_request, rules]
    - changes:
        - terraform/**/*

# Scanning top level modules to avoid extreme duplication
tfsec-check-soft:
  image: aquasec/tfsec-ci:v1.26.3
  script:
    - tfsec --no-color --soft-fail terraform/$TFDIR
  rules:
    - !reference [.merge_request, rules]
    - changes:
        - terraform/$TFDIR/**/*
  parallel:
    matrix:
      - TFDIR:
          - all/module
          - app
          - core/module
          - gitlab/module
          - modules
          - sms/module
          - tooling/module
          - waf/module
          - data-warehouse/module

# Add folders that should be vuln free and STAY THAT WAY
tfsec-check-enforce:
  image: aquasec/tfsec-ci:v1.26.3
  script:
    - tfsec --no-color terraform/$TFDIR
  rules:
    - !reference [.merge_request, rules]
    - changes:
        - terraform/$TFDIR/**/*
  parallel:
    matrix:
      - TFDIR:
          - imagebuild/module
          - master/module
          - tooling/module-gitlabpipeline
          - tooling/module-pipeline

users-yaml-validation:
  image: "$ECR_REGISTRY/ecr-public/docker/library/golang"
  rules:
    - !reference [.merge_request, rules]
    - changes:
      - terraform/master/global/users.yaml
  script:
    - cd bin/users
    - make validate

lambda-unit-tests:
  image: "$ECR_REGISTRY/ecr-public/docker/library/python:3.9.18-alpine3.18"
  script:
    - apk add --no-cache bash git
    - ./bin/lambda-utilities/test.sh --coverage --xml
  rules:
    - !reference [.merge_request, rules]
    - changes:
        - terraform/**/*
  coverage: '/TOTAL.* (100\%|\d\d\%)$/'
  artifacts:
    paths:
      - htmlcov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: tmp/unittest.xml

lambda-lint:
  image: "$ECR_REGISTRY/ecr-public/docker/library/python:3.9.18-alpine3.18"
  script:
    - apk add --no-cache bash git
    - ./bin/lambda-utilities/lint.sh
  rules:
    - !reference [.merge_request, rules]
    - changes:
        - terraform/**/*
