profile-md:
	trestle author profile-generate -n nist-sp-800-53-rev5-moderate -o dist/profiles/nist-sp-800-53-rev5-moderate

ssp-md:
	trestle author ssp-generate -p nist-sp-800-53-rev5-moderate -o dist/system-security-plans/nist-sp-800-53-rev5-moderate
