generate:
	trestle author ssp-generate -p nist-sp-800-53-rev5-moderate -o dist/system-security-plans/nist-sp-800-53-rev5-moderate

assemble:
	trestle author ssp-assemble --markdown dist/system-security-plans/ --output nist-sp-800-52-rev5-moderate
