---
# TODO: cache bundle artifacts

include:
  local: /.gitlab-ci-rules.yml

cloudlib_spec:
  image: cimg/ruby:3.0
  script:
    - bundle check || bundle install --deployment --jobs=4 --retry=3  --path vendor/bundle
    - bundle exec rspec cloudlib/spec
  rules:
    - !reference [.merge_request, rules]
    - changes:
        - cloudlib/**/*
