#!/usr/bin/env bash
#
# This script is designed to format the NVMe device attached to the EC2 instance
# and mount it to /var/lib/elasticsaerch for use by an elasticsearch cluster.
#

# get last unused nvme device
nvme_device_path=$(lsblk -sp | grep -E '^.dev.nvme.*disk $' | awk '{print $1}' | tail -1)

if [ -z "$nvme_device_path" ]
then
  echo 'No unused NVMe devices attached to this host'
else
  mkdir -p /var/lib/elasticsearch

  if mount "$nvme_device_path" /var/lib/elasticsearch 2>/dev/null
  then
    echo "it appears this device has already been formatted, so $nvme_device_path has been mounted on /var/lib/elasticsearch"
  else
    echo 'Formatting device as ext4 and mounting to /var/lib/elasticsearch'
    # format with ext4 fs
    mkfs.ext4 "$nvme_device_path"

    # mount device
    mount "$nvme_device_path" /var/lib/elasticsearch/
  fi
fi
