#!/usr/bin/env ruby
require 'json'
require 'jsonclient'

j = JSONClient.new

j.ssl_config.add_trust_ca('/etc/elasticsearch/root-ca.pem')

response = j.get('https://elasticsearch.login.gov.internal:9200/_xpack/license').body

license_status =  response.fetch('license').fetch('status')
license_type = response.fetch('license').fetch('type')
expiry_date = DateTime.parse response.fetch('license').fetch('expiry_date')

# true if license is valid for more than one month
license_current = ((expiry_date - DateTime.now).to_i > 30)

if license_type == 'platinum' && license_status == 'active' && license_current
  puts 'Current license is still active. No need to update license.'
else
  # post license
  file = File.read('/etc/xpack_license')
  post_data = JSON.parse(file)
  response = j.post('https://elasticsearch.login.gov.internal:9200/_xpack/license', post_data).body
  puts response
end
