source 'https://rubygems.org'

gem 'berkshelf', '~> 6.3'

# For Chefspec: https://github.com/sethvargo/chefspec
gem 'chefspec'

# For Test Kitchen: https://github.com/test-kitchen/test-kitchen
#gem 'test-kitchen'
#gem 'kitchen-ec2'
#gem 'kitchen-vagrant'
#gem 'kitchen-inspec'

# We need this in order to run rspec tests, which is weird since it's only used
# by dependency cookbooks.
gem 'aws-sdk-ec2', '~> 1.0'

gem 'chef', '~> 15.10.12'
