source 'https://rubygems.org'

gem 'berkshelf', '~> 6.3'

# For Chefspec: https://github.com/sethvargo/chefspec
gem 'chefspec'

# For Test Kitchen: https://github.com/test-kitchen/test-kitchen
#gem 'test-kitchen'
#gem 'kitchen-ec2'
#gem 'kitchen-vagrant'
#gem 'kitchen-inspec'

# not super clear why this is needed here when it's only used by dependency
# cookbooks
#gem 'aws-sdk'

gem 'chef', '~> 13.9'
