source 'https://rubygems.org'

gem 'berkshelf', '~> 7.0.9'

# For Chefspec: https://github.com/sethvargo/chefspec
gem 'chefspec', '>= 9.0.0'

# For Test Kitchen: https://github.com/test-kitchen/test-kitchen
gem 'test-kitchen', '~> 2.5'
gem 'kitchen-ec2', '~> 3.0.1'
gem 'kitchen-vagrant'
gem 'kitchen-inspec', '~> 1.1.0'
gem 'inspec', '~> 4.7.24'
gem 'rspec-retry'

# The default test-kitchen SSH transport is unusably slow
# (default ssh at ~760s vs. speedy_ssh at ~25s)
gem 'kitchen-transport-speedy', '~> 0.1'
# see also:
# gem 'kitchen-transport-sshtar'
# gem 'kitchen-transport-rsync'

gem 'chef', '~> 15.10.12'

# These are needed to build multipart cloud init data for test kitchen
gem 'mime'
gem 'erubis', '~> 2'

# EC2 API used for various lookups inside the kitchen.cloud.yml
gem 'aws-sdk-ec2', '~> 1.0'
