name             'identity-pivcac'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures identity-pivcac'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'identity_shared_attributes'
depends          'login_dot_gov'
depends          'deploy_resource'
