source 'https://api.berkshelf.com'

# Needed for `role[base]`

cookbook 'apt'
cookbook 'bash-completion'
cookbook 'build-essential'
cookbook 'cacert'
cookbook 'git'
cookbook 'hostname'
cookbook 'motd'
cookbook 'nano'
cookbook 'ruby_build'
cookbook 'ssh-keys'
cookbook 'sudo'

cookbook 'apt_update', path: '../../kitchen/cookbooks/apt_update'
cookbook 'identity-elk', path: '../../kitchen/cookbooks/identity-elk'
cookbook 'identity-jenkins', path: '../../kitchen/cookbooks/identity-jenkins'
cookbook 'identity-nessus', path: '../../kitchen/cookbooks/identity-nessus'
cookbook 'identity-ntp', path: '../../kitchen/cookbooks/identity-ntp'
cookbook 'identity-ossec', path: '../../kitchen/cookbooks/identity-ossec'
cookbook 'login_dot_gov', path: '../../kitchen/cookbooks/login_dot_gov'
cookbook 'config_loader', path: '../../kitchen/cookbooks/config_loader'

# Needed by the config_loader cookbook

# We have to reference this special citadel-build repository for two reasons:
#
# 1. We have a custom fork of https://github.com/poise/citadel at
#    https://github.com/18f/citadel.git because of
#    https://github.com/poise/citadel/pull/35 and
#    https://github.com/poise/citadel/pull/36.
# 2. There is an extra build step required, and the citadel repository itself is
#    a valid cookbook.  See the citadel-build repository for more details.  This
#    worked before without this extra repo because we were pulling the built
#    citadel from https://supermarket.chef.io.
#
# Once the pull requests are merged and a new citadel version is released we can
# get rid of this.
cookbook 'citadel_fork', '~> 9.1.1', git: 'https://github.com/18f/citadel-build.git'

# Needed only for Jumphost

cookbook 'identity-jumphost', path: '../../kitchen/cookbooks/identity-jumphost'
