name             'identity-gitlab'
maintainer       '18f identity'
maintainer_email 'developer@login.gov'
description      'Installs/Configures identity-gitlab'
version          '0.0.5'

depends 'config_loader'
depends 'filesystem'
depends 'docker'
depends	'login_dot_gov'
depends 'packagecloud'
