source 'https://rubygems.org'

gem 'berkshelf', '~> 4.3'

# For Chefspec: https://github.com/sethvargo/chefspec
gem 'chefspec'

# For Test Kitchen: https://github.com/test-kitchen/test-kitchen
gem 'test-kitchen'
gem 'kitchen-ec2'
gem 'kitchen-vagrant'
gem 'kitchen-inspec'
gem 'kitchen-transport-sshtar'

gem 'chef', '= 12.15.19'
