# -- SES identity --

resource "aws_ses_domain_identity" "primary" {
  domain = "humans.login.gov"
}

resource "aws_ses_domain_dkim" "primary" {
  domain = aws_ses_domain_identity.primary.domain
}

# -- DKIM Tokens --

output "ses_token" {
  description = "Token for the primary verification record in Route 53."
  value       = aws_ses_domain_identity.primary.verification_token
}

output "dkim_tokens" {
  description = <<EOM
DKIM tokens generated by SES to be created as Route53 records in login.gov HostedZone
EOM
  value = zipmap(
    formatlist(
      "%s._domainkey.${aws_ses_domain_identity.primary.domain}",
      aws_ses_domain_dkim.primary.dkim_tokens
    ),
    formatlist(
      "%s.dkim.amazonses.com",
      aws_ses_domain_dkim.primary.dkim_tokens
    ),
  )
}