# -- SES identity --

resource "aws_ses_domain_identity" "primary" {
  domain = "humans.login.gov"
}

resource "aws_ses_domain_dkim" "primary" {
  domain = aws_ses_domain_identity.primary.domain
}

# -- DKIM Tokens --

output "ses_token" {
  description = "Token for the primary verification record in Route 53."
  value       = aws_ses_domain_identity.primary.verification_token
}

output "dkim_first_token_name" {
  description = "DKIM tokens generated by SES to be created as R53 records in login.gov hosted zone"
  value       = ["${aws_ses_domain_dkim.primary.dkim_tokens[0]}._domainkey.${aws_ses_domain_identity.primary.domain}"]
}

output "dkim_first_token_value" {
  description = "DKIM tokens generated by SES to be created as R53 records in login.gov hosted zone"
  value       = ["${aws_ses_domain_dkim.primary.dkim_tokens[0]}.dkim.amazonses.com"]
}

output "dkim_second_token_name" {
  description = "DKIM tokens generated by SES to be created as R53 records in login.gov hosted zone"
  value       = ["${aws_ses_domain_dkim.primary.dkim_tokens[1]}._domainkey.${aws_ses_domain_identity.primary.domain}"]
}

output "dkim_second_token_value" {
  description = "DKIM tokens generated by SES to be created as R53 records in login.gov hosted zone"
  value       = ["${aws_ses_domain_dkim.primary.dkim_tokens[1]}.dkim.amazonses.com"]
}

output "dkim_third_token_name" {
  description = "DKIM tokens generated by SES to be created as R53 records in login.gov hosted zone"
  value       = ["${aws_ses_domain_dkim.primary.dkim_tokens[2]}._domainkey.${aws_ses_domain_identity.primary.domain}"]
}

output "dkim_third_token_value" {
  description = "DKIM tokens generated by SES to be created as R53 records in login.gov hosted zone"
  value       = ["${aws_ses_domain_dkim.primary.dkim_tokens[2]}.dkim.amazonses.com"]
}