variables:
  GITHUB_ENDPOINT: "https://#{EXTERNAL_FQDN}:443"
  GITLAB_ADMIN_PASSWORD: ${GITLAB_QA_PASSWORD}
  GITLAB_ADMIN_USERNAME: ${GITLAB_QA_ACCOUNT}
  GITLAB_API_BASE: "https://#{EXTERNAL_FQDN}/api/v4"
  GITLAB_FORKER_PASSWORD: ${GITLAB_QA_PASSWORD}
  GITLAB_FORKER_USERNAME: ${GITLAB_QA_ACCOUNT}
  GITLAB_PASSWORD: ${GITLAB_QA_PASSWORD}
  GITLAB_QA_PASSWORD: ${GITLAB_QA_PASSWORD}
  GITLAB_QA_USERNAME_1: ${GITLAB_QA_ACCOUNT}
  GITLAB_USERNAME: ${GITLAB_QA_ACCOUNT}
  QA_DEBUG: "true"

gitlab-qa:
  tags:
    - build-pool
  image: 034795980528.dkr.ecr.us-west-2.amazonaws.com/gitlab-qa:latest
  stage: build
  script:
    - echo "Yay!"
