output "last_receipt_rule" {
  value       = element(aws_ses_receipt_rule.usps_per_env, length(aws_ses_receipt_rule.usps_per_env) - 1).name
  description = "The last receipt rule generated by this module. This should be used with external receipt rules to determine ordering"
}
