#!/bin/bash
#
# Rerun this recipe from cron.
#
set -eu

while getopts e: opt
do
  case $opt in
    e) ENV="${OPTARG}"   ;;
   \?) exit 1            ;;
  esac
done
shift $((OPTIND-1))

if [[ -z "${ENV:-}" ]]; then
  echo "Must specify ENVIRONMENT (-e)" >&2
  exit 1
fi

# Set AWS Account/Region
PROD_ENVIRONMENTS=("prod" "staging" "dm")
AWS_ACCOUNT_NUM=""

if [[ " ${PROD_ENVIRONMENTS[@]} " =~ " ${ENV} " ]]; then
  AWS_ACCOUNT_NUM="555546682965"
else
  AWS_ACCOUNT_NUM="894947205914"
fi

[ -e /root/letsencrypt.${ENV}.tar.gz ] && rm -f /root/letsencrypt.${ENV}.tar.gz

aws s3 cp s3://login-gov-pivcac-${ENV}.${AWS_ACCOUNT_NUM}-us-west-2/letsencrypt.${ENV}.tar.gz /root/letsencrypt.${ENV}.tar.gz

cd /etc/letsencrypt

#[ -s /root/letsencrypt.${ENV}.tar.gz ] && tar zxf /root/letsencrypt.${ENV}.tar.gz || certbot certonly --agree-tos -n --dns-route53 -d *.pivcac.${ENV}.identitysandbox.gov --email identity-devops@login.gov --server https://acme-v02.api.letsencrypt.org/directory --deploy-hook "/usr/local/bin/push_letsencrypt_certs.sh -e ${ENV}" --preferred-chain 'ISRG Root X1'  --key-type rsa --rsa-key-size 2048

certbot renew -n --deploy-hook "/usr/local/bin/push_letsencrypt_certs.sh -e ${ENV}" --preferred-chain 'ISRG Root X1' --key-type rsa --rsa-key-size 2048
