#!/bin/bash
#
# Rerun this recipe from cron.
#
set -eu

while getopts e:c: opt
do
  case $opt in
    c) CERT_ENV="${OPTARG}" ;;
    e) ENV="${OPTARG}"      ;;
   \?) exit 1               ;;
  esac
done
shift $((OPTIND-1))

if [[ -z "${ENV:-}" ]]; then
  echo "Must specify ENVIRONMENT (-e)" >&2
  exit 1
fi

if [[ -z "${CERT_ENV:-}" ]]; then
  CERT_ENV=$ENV
fi

# Set AWS Account/Region
PROD_ENVIRONMENTS=("prod" "staging" "dm")
AWS_ACCOUNT_NUM=""

if [[ " ${PROD_ENVIRONMENTS[@]} " =~ " ${ENV} " ]]; then
  AWS_ACCOUNT_NUM="555546682965"
else
  AWS_ACCOUNT_NUM="894947205914"
fi

# Set domains that PIVCAC cert will be requested for. Review-app environment uses a different domain structure
# than other environments, so we test to see if ENV is reviewapp to set it's value, otherwise the domain follows
# standard PIVCAC domain structure.
CERT_DOMAIN=""
if [[ "${ENV}" = "reviewapp" ]]; then
  CERT_DOMAIN="-d *.${CERT_ENV}.pivcac.identitysandbox.gov"
else
  CERT_DOMAIN="-d pivcac.${CERT_ENV}.identitysandbox.gov -d *.pivcac.${CERT_ENV}.identitysandbox.gov"
fi

if [[ -z "${CERT_DOMAIN:-}" ]]; then
  echo "Certificate Domain did not get set properly. This error should not happen. Troubleshoot script"
  exit 1
fi

[ -e /root/letsencrypt.${CERT_ENV}.tar.gz ] && rm -f /root/letsencrypt.${CERT_ENV}.tar.gz

aws s3 cp s3://login-gov-pivcac-${ENV}.${AWS_ACCOUNT_NUM}-us-west-2/letsencrypt.${CERT_ENV}.tar.gz /root/letsencrypt.${CERT_ENV}.tar.gz

cd /etc/letsencrypt

[ -s /root/letsencrypt.${CERT_ENV}.tar.gz ] && tar zxf /root/letsencrypt.${CERT_ENV}.tar.gz || certbot certonly --agree-tos -n --dns-route53 ${CERT_DOMAIN} --email identity-devops@login.gov --server https://acme-v02.api.letsencrypt.org/directory --deploy-hook "/usr/local/bin/push_letsencrypt_certs.sh -e ${ENV} -c ${CERT_ENV}" --preferred-chain 'ISRG Root X1'  --key-type rsa --rsa-key-size 2048

certbot renew -n --deploy-hook "/usr/local/bin/push_letsencrypt_certs.sh -e ${ENV} -c ${CERT_ENV}" --preferred-chain 'ISRG Root X1' --key-type rsa --rsa-key-size 2048
