source 'https://rubygems.org'

gem 'berkshelf', '~> 7.1.0'

# For Test Kitchen: https://github.com/test-kitchen/test-kitchen
gem 'test-kitchen'
gem 'kitchen-ec2'
gem 'kitchen-inspec'

gem 'chef', '~> 15.12.22'
