# frozen_string_literal: true

ruby "~> 3.2.0"

source 'https://rubygems.org'

group 'test' do
  gem 'rspec', '~> 3.10'
  gem 'rspec_junit_formatter', '~> 0.4'
end

gem 'aws-sdk-dynamodb', '~> 1'
gem 'rexml'
